### ISSUE TITLE
Fails after Tensor Fitting intermittently

### ISSUE THREAD

**Issue by kaytiii** [m-ama/PyDesigner#142]
**Describe the Issue**

PyDesigner fails after tensor fitting ~70% of the time. It is often possible to rerun failed subjects successfully. Sometimes a subject's data will fail to process past tensor fitting once, sometimes as many as 5+ times.

There's no discernible difference in data setup or quality between subjects. 

**Issue Reproduction**

The following command was implemented in a loop for all subjects in my dataset: 

`python pydesigner.py --denoise --degibbs --mask --force DKI.nii,B0.nii -o [output path]`

This is the entirety of the output: 

```
Computing SNR: raw_dwi.nii
   * B0...
   * B1000...
   * B2000...
Computing SNR: preprocessed_dwi.nii
   * B0...
   * B1000...
   * B2000...
Image preprocessed_dwi.nii loaded successfully
Processing with 6 workers...
IRLLS: Noise Estimation : 100%|█| 109511/109511 [00:13<00:00, 8363.25vox/s]
IRLLS: Outlier Detection: 100%|█| 109511/109511 [02:58<00:00, 612.20vox/s]
Constrained Tensor Fit  : 100%|█| 109511/109511 [04:43<00:00, 385.97vox/s]
Traceback (most recent call last):
  File "/Users/kayti/Repos/PyDesigner/designer/pydesigner.py", line 755, in <module>
    img.fit(fit_constraints, reject=outliers)
  File "/Users/kayti/Repos/PyDesigner/designer/fitting/dwipy.py", line 605, in fit
    self.dt = np.reshape(self.dt, (dwi_.shape[1], self.b.shape[1])).T
  File "<__array_function__ internals>", line 6, in reshape
  File "/Users/kayti/anaconda3/envs/dmri/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/kayti/anaconda3/envs/dmri/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/kayti/anaconda3/envs/dmri/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 109511 into shape (109511,22)
```

**Supplemental Information**

**Comment by TheJaeger** [comment]
Issue arises because somewhere along the way through thousands of linear least squares fitting; a missing or NaN value throws off the Intel Math Kernel Library (MKL). These errors, by default, are hidden from the user and makes it appear that everything is fine when it's not.

This is is a well-known problem with Numpy in Python and unfortunately there is not much we can do to fix it. The only thing that we can do is to check each line of code in tensor estimation (among hundreds of lines) and replace NaNs with zeros. This will require an extensive amount of effort, but is most likely the only way without forcing users to manually compile and Python modules or changing their environment.
