### ISSUE TITLE
Dataset deemed DTI-type, but actually DKI

### ISSUE THREAD

**Issue by j-tseng** [m-ama/PyDesigner#254]
**Describe the Issue**
Only DTI metric maps are produced by the pipeline but we have 3 b-shell values (1000, 1600, 2600). Debugging reveals that the img is assigned DTI-type because `isDKI()` is false, as our highest value b-shell is greater than the maximum DKI bval threshold in `fitting/thresholds.py` (line 3), and thereby excluded when determining the max b-value (`fitting/dwipy.py` line 216). 

Is there a particular reason why the threshold is set at 2.5?

**Issue Reproduction**

Here's the pydesigner terminal call:
```bash
pydesigner --verbose -o $outfolder/$p \
			   -n --extent 5,5,5 \
			   -g -r -u --rpe_pairs 1 \
		  	   -z --fwhm 1.2 \
			   --noakc --nooutliers --adv \
		   	   $infiles
```

**Comment by TheJaeger** [comment]
Hi @j-tseng, we have it set to 2500 because our lab generally caps DKI b-value at <2500. You are right, your b-value of 2600 is well below b_max=3000 s/mm^2, and so it should be a DKI sequence.

I'll make these changes and push them into PyDesigner v1.0-RC10. It may take a week or two though because I am also working on muti-TE support for RC10. In the meantime, you can re-download the latest release of PyDesigner, and change line 3 in _designer/fitting/thresholds.py_ to __maxdkibval__ = 3.0. For your reference, this line can be found on https://github.com/m-ama/PyDesigner/blob/ea7a3c4b034bcc537e233848d2e3a5e1bfcc1214/designer/fitting/thresholds.py#L3

You may reinstall PyDesigner using this workaround for the time being till RC10 is released.

**Comment by j-tseng** [comment]
Thanks for the speedy reply, @TheJaeger! Modifying that line did yield the DKI and WMTI outputs.
