### ISSUE TITLE
Util.py possible missing "self." 

### ISSUE THREAD

**Issue by tmspvn** [m-ama/PyDesigner#264]
Hi,

PyDesigner returned "JSONlist" not defined for line 466 of util.py:

`root@139519c15f53:/home/WORKDIR# pydesigner --denoise --nofit /home/WORKDIR/LOCAL_DATA/preproc/sub/diff_raw.nii.gz
/opt/miniconda-latest/envs/pyd/lib/python3.8/site-packages/PyDesigner-1.0rc10-py3.8.egg/designer/preprocessing/util.py:31: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if pathname is '':
/opt/miniconda-latest/envs/pyd/lib/python3.8/site-packages/PyDesigner-1.0rc10-py3.8.egg/designer/preprocessing/util.py:466: UserWarning: JSON file(s) ['/home/WORKDIR/LOCAL_DATA/preproc/sub/diff_raw.json'] not found. Attempting to process without. If processing fails, please use the "--adv" flag
  warnings.warn('JSON file(s) {} not found. '`

After adding changing "JSONlist" to "self.JSONlist" it works. 

Not sure if that actually fixes the problem or just circumvent it tho.

Thanks

**Comment by TheJaeger** [comment]
Hi @tmspvn, it appears that you do not have a valid .json BIDS sidecar accompanying your dataset. If present, it needs to have the same name as your input DWI.

**Comment by tmspvn** [comment]
The data is not in BIDS format hence I don't have the JSON, how would you proceed?

**Comment by TheJaeger** [comment]
Were you able to solve the issue?

The only way to process without JSON is to use DICOM files directly, or to reconvert your files to NifTi with JSON sidecar using dcm2niix. There is currently no way to process NifTi files without JSON information. The fix you posted above bypasses the check, but it's not recommended since PyD uses information encoded in JSON to make certain decisions on processing.

**Comment by tmspvn** [comment]
Hi, No i don't have the dicoms yet. Soon I will receive them and I will update this comment if I will be able to solve. Thanks
