### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by override641** [m-ama/PyDesigner#277]
**Describe the Issue**

when running pydesigner -s and i use separete b0 image and then multishell B0,1000,2000 image, I always get the following error 

Plotting motion...
Traceback (most recent call last):
  File "/usr/local/bin/pydesigner", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/designer/pydesigner.py", line 666, in main
    voxel=mrinfoutil.spacing(working_path))
  File "/usr/local/lib/python3.7/dist-packages/designer/plotting/motionplot.py", line 33, in plot
    raise OSError('Input file {} does not exist'.format(input))
OSError: Input file /data/processed/metrics_qc/eddy/eddy_restricted_movement_rms does not exist

**Issue Reproduction**
run the pydesigner -s with separate b0 and b0,1000 and b2000

**Supplemental Information**

MacOS, pydesigner 1.0 RC11

Thank you

**Comment by TheJaeger** [comment]
Hi, what was the full command you parsed?

**Comment by override641** [comment]
Hi!

pydesigner -s —verbose DWI0.nii,DWI1.nii

while DWI0 is b0 image and DWI1 is b0,1000,2000
if I run it with the DWI1, it runs ok. 

THank you
Ivo

**Comment by TheJaeger** [comment]
PyDesigner is looking for the file `/data/processed/metrics_qc/eddy/eddy_restricted_movement_rms` to plot head motion, which is produced during topup/eddy current correction. I'd check `intermediate_files` folder to ensure this correction ran properly, as well as the PyDesigner log while this correction was running. Something could have silently failed along the way.

Otherwise you can parse the `--no_qc` flag to disable plots and bypass the error.
