### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by override641** [m-ama/PyDesigner#279]
**Describe the Issue**
Thank you for your help, all other issues resolved without my intervention, just with time. However I am stuck here:

mrmath: [100%] preloading data for "/data/processed/B0_ALL.mif"
mrmath: [100%] computing mean along axis 3...
mrcalc: [100%] computing: (finite (/data/processed/B0_MEAN.mif) ? /data/processed/B0_MEAN.mif : 0)
Computing SNR: dwi_raw.nii
   * B0...
   * B1000...
   * B2000...
Computing SNR: dwi_preprocessed.nii
   * B0...
   * B1000...
   * B2000...
Traceback (most recent call last):
  File "/usr/local/bin/pydesigner", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/designer/pydesigner.py", line 943, in main
    nthreads=args.nthreads
  File "/usr/local/lib/python3.7/dist-packages/designer/fitting/dwipy.py", line 2708, in fit_regime
    img = DWI(input, mask=mask, nthreads=nthreads)
  File "/usr/local/lib/python3.7/dist-packages/designer/fitting/dwipy.py", line 66, in __init__
    if not os.path.exists(imPath):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

This only occurs when I use separe B0 image for RPE purposes. If I parse without second DWI I wont get this error. I ran it on multiple patients, however no luck, it happens 100% of time. Running it in Dock with --standard on Mac. 

Thank you very much for your amazing support!
Merry Xmas!

**Comment by TheJaeger** [comment]
Could you share this dataset with me at siddhartha.dhiman@gmail.com? I need to debug the code with your dataset to figure out why this error is being produced.

**Comment by TheJaeger** [comment]
Hey @override641, the latest PyDesigner release v.10-RC12 fixes the issue you were having. The problem occurs because your DWI and reverse phase encoded (RPE) acquisitions have different echo times (TE) - 105 and 98 ms, respectively. This threw PyDesigner's logic off because it was trying to process your the different TEs separately.

PyDesigner concatenates all input volumes (DWI + RPE) into one 4D volume, and preprocessed them together i.e. all of them undergo denoising and Gibbs unringing prior to undistortion. These volumes stay together till the very end because once corrected, all of them can contribute to linear least squares (LLS) tensor fitting. Having said that, the presence of having b0 volumes at different TEs can skew the fitting, and result in inaccurate DTI/DKI metrics. I'd advise you to revise your protocol so that your RPE and DWI are acquired at the same TE.

**Comment by override641** [comment]
Thank you very much ! 

Best regards,
Ivo Petö
