### ISSUE TITLE
Necessity of `-it --rm` flags when running from docker

### ISSUE THREAD

**Issue by AvantiShri** [m-ama/PyDesigner#319]
Hi, I was trying to run pydesigner on a remote machine via an internal job management system, and was wondering about what happens if the "-it --rm" flags are excluded (the current version of the docs says that we need those flags to "run docker in interative TTY mode"). I ask because my script called the docker container from a shell spawned by python's subprocess module, and because that wasn't a tty shell I had to remove those flags to get the job to run - however, the job has stalled and I am not sure whether it has to do with excluding those flags, so just thought I'd ask in case you have a quick answer.

Thanks,
Avanti

**Comment by gonzoBlackMamba** [comment]
Hi @AvantiShri 

Did the job ever finish? The longest portion is the eddy and undistortion part of the code. Depending on how many image volumes are in the DWI series, it could take 20 minutes or a day since docker is limited by the resources you allow it. Also, if you have access to python, then you shouldn't need to run it on Docker, is there a reason you can't run PyDesigner directly (w/o Docker) on the remote machine?

-Hunter

**Comment by AvantiShri** [comment]
Hi Hunter, sorry for the slow response. The job did finish when I reran it. The reason we are using docker is that there are dozens of machines and it's easier to ensure the correct dependencies are present (and avoid dependency conflicts with other people using the machines for different things) if we run it via docker. Thanks!
